### ISSUE TITLE
[Request] Creating CI workflow file to build wheels to support different arch and py ver.

### ISSUE THREAD

**Issue by FinBird** [Vizonex/Winloop#1]
Hello Vizonex, I found this project very useful for me. 
I request your help to creating a CI workflow file to automate the build process for wheels, including support for win32 and different py ver(py3.9-py3.12?). This would greatly benefit users who are running systems with 32-bit Windows architecture without building it by themselves. Thank you for your work!

**Comment by Vizonex** [comment]
Glad you asked :)
I haven't looked into it yet and I don't know how to implement it. Do you have any ideas or suggestions how we could do that?

**Comment by Vizonex** [comment]
No doubt I will have to do more research on this when I have the time to. I'll leave this issue opened until you and I are able to solve it.

**Comment by FinBird** [comment]
I Take a try but fail
https://github.com/FinBird/Winloop/blob/main/.github/workflows/publish.yml
Becasue I Can't build it on my machine, so I just take a try online.
Where is the .whl located after the following command run? 
https://github.com/FinBird/Winloop/blob/a8a4186313ec7fcda0056020028f3bc8527a64f7/.github/workflows/publish.yml#L36
See it
https://github.com/FinBird/Winloop/actions/runs/5290975301

**Comment by Vizonex** [comment]
I'm not sure where it is perhaps a video if it exists will help us determine this but I'm very glad to see that you may have ended up figuring it out a lot of this before I could get to it. I did end up finding an article as well if that helps any https://andrewpwheeler.com/2022/05/10/building-wheel-files-in-github-actions/ as well.

If you need even more help I can always add my discord server to either my about me page or this repo if that will help us out better.
I also know of some guys that could also help us with this and I actually gave him a shoutout for figuring out how to install everything for this library correctly.

**Comment by Vizonex** [comment]
![image](https://github.com/Vizonex/Winloop/assets/114684698/5e6f477e-46ad-41c3-a695-8e3a599b064c)
I may have just now found your problem.

**Comment by Vizonex** [comment]
Another thing that I haven't done yet is link pypi straight to this repo rather than running twine from my system which maybe our next big problem because if I'm not there and another contributor wants to update everything how will they go about it? I'll be sure to also do that as well.

**Comment by Vizonex** [comment]
@FinBird https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac Have you tried this yet?

**Comment by FinBird** [comment]
> @FinBird https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac Have you tried this yet? Something I always try to do is look up the error word for word in a search engine  like tor to figure these things out. Let me link my discord server in the repository and maybe we can talk about this further at some point...

Thanks for figure it out, I am repairing it now.

**Comment by Vizonex** [comment]
You're welcome :)

**Comment by Vizonex** [comment]
https://github.com/FinBird/Winloop/actions/runs/5290975301/jobs/9580068368 if you go here you'll see the issues... It seems that this might fix one of them... https://stackoverflow.com/questions/57361723/error-when-pull-or-push-to-git-enoent-no-such-file-or-directory#58162631

**Comment by Vizonex** [comment]
https://stackoverflow.com/questions/65014768/cant-find-my-python-module-after-installing-on-github-actions
I found another thing you should look into

**Comment by Vizonex** [comment]
@FinBird I added my pypi token for winloop now so any releases I do should in fact work...
https://youtube.com/watch?v=d1qS3ZWS7WY

**Comment by Vizonex** [comment]
@FinBird Since I now added my token for Publishing so everything should now work for us on this end and you should be able to now do a Pull Request and I'll update the pypi package with more wheels for 0.0.7 and close this issue down.

**Comment by FinBird** [comment]
> @FinBird Since I now added my token for Publishing so everything should now work for us on this end and you should be able to now do a Pull Request and I'll update the pypi package with more wheels for 0.0.7 and close this issue down.
> I expected pypi not to work but now that I've added my token over here it will in fact be sucessful.

See [https://github.com/Vizonex/Winloop/pull/2](Pull #1)

**Comment by Vizonex** [comment]
Great Job! I'll update it soon with the new wheels.
