### ISSUE TITLE
Winloop is not work in uvicorn multiprocessing

### ISSUE THREAD

**Issue by yangy996** [Vizonex/Winloop#11]
In uvicorn, I have added a new file “winloop.py”.
![image](https://github.com/Vizonex/Winloop/assets/15188456/13e3cd91-de78-4116-977b-995af5e1009a)
uvicorn/config.py:
![image](https://github.com/Vizonex/Winloop/assets/15188456/c6b15843-d463-4c86-84a9-41c0d924c820)

Next:
    from uvicorn import run
    run("app_compat:create_app_fastapi", host="0.0.0.0",
        workers=int(args["workers"]),
        port=int(port),
        loop="winloop",
        factory=True)

Result:
![image](https://github.com/Vizonex/Winloop/assets/15188456/82f58298-f694-40e5-ae05-e8a95d1752de)
Pid is 23052 and 4604.

Just,It is only running on PID 4604.

**Comment by Vizonex** [comment]
@yangy996 There is still some work to be done around multiprocessing including `aiomultiprocessing` . Even I am having trouble understanding why it fails to work. We had an update recently so if you are on it, try using it and then see if you're still having the same issue. I am working on writing a `unittest` soon for multiprocessing problems in general. Try using version `0.1.0` to help you figure out if these problems still exists.

**Comment by yangy996** [comment]
> @yangy996 There is still some work to be done around multiprocessing including `aiomultiprocessing` . Even I am having trouble understanding why it fails to work. We had an update recently so if you are on it, try using it and then see if you're still having the same issue. I am working on writing a `unittest` soon for multiprocessing problems in general. Try using version `0.1.0` to help you figure out if these problems still exists.

The current version is 0.1.0.

**Comment by Vizonex** [comment]
I am currently dealing with the blue-screen of death at the moment on my pc so your going to have to wait until I can fix it. I apologize for the inconvenience at the moment. 
![797DACF6-26DD-44B6-B7F5-7C81DB4D7686](https://github.com/Vizonex/Winloop/assets/114684698/cb54faeb-9d81-4a5e-9b53-2e0d69c3907d)

When I get this problem solved I plan to first test aiomultiproccess and then go in by debugging everything step by step at a time until it finally works correctly.

**Comment by Vizonex** [comment]
@yangy996 `aiomultiproccessing` and `multiproccessing` works fine now since our update so I guess my friend fixed it #14 And I just uploaded test suite on top of that. I would like your conformation first though before I decide close this issue.

**Comment by yangy996** [comment]
The current version is 0.1.1
It is not work.
![S2FCC32728 CJ_UNX}VYBUC](https://github.com/Vizonex/Winloop/assets/15188456/702148c3-6c9d-41a8-8249-bd6d7ff15a62)

**Comment by Vizonex** [comment]
I was able to get it to spawn in 2 pids using a test via the aiomultiprocess library I will try to extend this into uvicorn very soon.

**Comment by Vizonex** [comment]
I'm closing this issue because we solved this one a long time ago.
