### ISSUE TITLE
Typo breaking compilation.

### ISSUE THREAD

**Issue by lschoe** [Vizonex/Winloop#16]
Hi, this typo "`ffrom`" breaks compilation (since change of two days ago):

https://github.com/Vizonex/Winloop/blob/b60cd2b11cec890300df9d0230a10f7776f6f2bd/winloop/includes/system.pxd#L1

Fixing it restores compilation.

**Comment by Vizonex** [comment]
@lschoe Hold On I will fix that real quick thanks for pointing this out to me

**Comment by Vizonex** [comment]
@lschoe Fixed https://github.com/Vizonex/Winloop/commit/0cf7326e6584aa8e538b351c8e0c743f9163072a
