### ISSUE TITLE
Winloop's workflow did not Compile Sucessfully 0.1.4

### ISSUE THREAD

**Issue by Vizonex** [Vizonex/Winloop#28]
I don't know how to install the vendor directory for libuv's workflow, might work on this tomorrow unless someone has already got a solution for how to do it

**Comment by Vizonex** [comment]
See: https://github.com/Vizonex/Winloop/actions/runs/9280037412

**Comment by lschoe** [comment]
I didn't see this issue, but yesterday I managed to fix the publish workflow by adding the use of submodules, and v0.1.4 is now on PyPI.
