### ISSUE TITLE
Update Cython to support Python 3.13?

### ISSUE THREAD

**Issue by shBLOCK** [Vizonex/Winloop#36]
Currently, installing Winloop on Python 3.13 results in compilation errors.
These errors are caused by Cython and were fixed in Cython 3.0.11.

To my understanding, this project is suitable for Cython 3.x? (except for spamming `warn.deprecated.DEF` warnings)
If so, we should consider updating to Cython 3.0.11+

**Comment by lschoe** [comment]
Just released Winloop version 0.1.7 on PyPi with support for Python 3.13, which required the move from Cython 0.29 to Cython 3.0 indeed (uvloop 0.21 has also made this transition recently).
