### ISSUE TITLE
Conditional Variables will soon be deprecated soon any workarounds?

### ISSUE THREAD

**Issue by Vizonex** [Vizonex/Winloop#5]
I have spoken to Scoder one of the Cython developers and It seems I have no response for solving the [Macro issue](https://github.com/cython/cython/issues/4310#issuecomment-1694484715) Does anyone have any ideas or workarounds to this where we would be able to keep the keywords in the script because otherwise we will have more problems in the future with future updates and we don't want for that to happen. If anyone can fork this repo and come up with a solution please reply to me about it. I do have one idea but it would be a pain because we would have to replace all the numbers but then telling people what they are would be a pain to implement (which implies that we would need More Documentation in the long run...) with `DEF` gone we need a clear and ALL-Out solution to this issue because uvloop is in the same boat as us...

**Comment by lschoe** [comment]
This issue can be closed as we have now migrated to Cython 3.0.
